### ISSUE TITLE
Import error message

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#153]
Hi Tim,

I've tested your suggested "if" statement format using a small sample data set and it looks like it's solved the problem I had. 

I've now got the whole corrected Langrivier water level record in a state that's ready for upload and have been trying to do that. The file is in csv format and my attempts resulted in some error messages that I was able to understand and figure out. I've however now run into one I don't understand. It seems to have something to do with the "if" statement. See below. Any ideas?

The "data source" code is JNHK_LANG_W_OTT_OM_WL_AVE if you'd like to check the transformation configuration.

![import error](https://user-images.githubusercontent.com/8395262/51315823-c3277580-1a5b-11e9-89aa-78da80fce2b6.JPG)

**Comment by TimPN-SAEON** [comment]
Hi Abri

Busy doing a backup, zip and transfer to my side. Once I have restored the backup I will have a look. Process normally takes 8 hours, so will only get to it tomorrow.

Tim

**Comment by TimPN-SAEON** [comment]
Hi Abri

The problem is the last if, it should have a comma and the equation for values > 2.14. Something like this:
if(value <= 0.399, a + b*value + c*pow(value,2) + d*pow(value,3) + e*pow(value,4),
if(value <= 0.6, f + g*value + h*pow(value,2) + i*pow(value,3),
if(value <= 1.09,  j + k*value + l*pow(value,2) +  m*pow(value,3),
if(value <= 1.52,  n + o*value + p*pow(value,2) +  q*pow(value,3),
if(value <= 2.14,  r + s*value + t*pow(value,2) +  u*pow(value,3) + v*pow(value,4),
-1)))))

Replace the -1 with the equation.

Regards

Tim

**Comment by TimPN-SAEON** [comment]
Hi Abri

I hope I am not missing something, but you have 5 break values, which implies you need 6 formulae to handle the whole range, the last to replace the -1.

Regards

Tim

**Comment by Abrisaeon** [comment]
Hi Tim,

You're not missing anything. I was. 

The discharge table equation that we have doesn't specify anything for water levels higher than 2.14 because at that height it's completely overflowing the weir and not passing though a restricted space of known dimensions.

So I think what I'll do is just use NA in the place of -1 and see if that works.

**Comment by Abrisaeon** [comment]
Ok, tried that and it doesn't accept text. I'll use -1.
