### ISSUE TITLE
Linking stations to sites

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#169]
Hi Tim,

I'm working with Wynand from Arid Lands this week for some training on the ObsDB and we're going through the process of setting up a test weather station. I've noticed some things that I think we can improve.

Firstly, when setting up a Station, the "Station detail" box allows you to link the station to a site. The feature works fine, but other links (to Instrument, Project and Organization) are done with the tabs provided on the background page (not part of the "Station detail" box). This is probably a leftover from how the database was designed, but I think it would be easier to keep track of what has been linked (and where to go to ensure it has) if these are all in the same place. I'd recommend moving the "Site" link to the row of tabs next to  Instrument, Project and Organization if possible. This is obviously not an urgent need, so have a look and see if you agree when convenient.

Secondly, we can link a Site to a Station (as described above), but when we go back to the Sites tab to see one sees a Stations and Organizations tab at the bottom which are supposed to show the links. The Stations tab does not update to show the new link (activated from Sites as described above) and the refresh button only refreshes the list of sites. This keeps the Stations-Site link invisible. If you then click on "Link Stations" the list of options is blank. There are no "Available stations" to select.

Having said that, you can see that the database allows us to link stations and sites in two ways, ie, from the Add Stations "station detail" box and also from the Add Sites page via the Link stations button. Should we eliminate this redundancy?

**Comment by TimPN-SAEON** [comment]
Hi Abri

The reason for the weirdness with Site/Station is that a Station can only have 1 site, hence the dropdown. The other links are many to many, that is why you can do it from either side.

On the Sites side I will remove the Link Stations button as there are never available stations because Site is required for a Station.

As for the tabs and refreshing, each tab is ignorant of changes in the other tabs. Unfortunately I have no control over that.  What you can do is try close the tab and reopen. Let me know if that doesn't work.
